"""Train a RandomForest classifier over the NASA GLC event catalog.

Reads the enriched GLC dataset (positives) + generated negatives, trains a
RandomForestClassifier, evaluates on a spatial holdout (by design the data pack
§2 warns against random splits because neighbouring pixels leak), and saves
the model artifact for use by ``ml_scoring.MLScorer``.

The data pack says: "Use Random Forest / XGBoost for a hackathon-feasible
first model." XGBoost is not in the environment; scikit-learn RandomForest is.

Usage:
    python train_ml_model.py

If real data is not available (no network), the script falls back to
synthetic data generated by ``generate_negative_samples._synthetic_positives``
so the model artifact is always produced.
"""
import logging
import pickle
import sys
from pathlib import Path

import numpy as np
import pandas as pd
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report
from sklearn.model_selection import GroupKFold

from config import CONFIG

logger = logging.getLogger(__name__)

# ML feature columns from data-pack §2 "Target Model Schema".
FEATURE_COLUMNS = [
    "rain_1d_mm", "rain_3d_mm", "rain_7d_mm", "rain_30d_mm",
    "elevation_m", "slope_deg", "aspect_deg", "curvature",
    "susceptibility_class", "lulc_class", "vegetation_proxy",
]

DEFAULT_NEGATIVES_PATH = Path("negative_samples.csv")
DEFAULT_TRAINING_PATH = Path("training_data_ml.csv")
DEFAULT_MODEL_PATH = Path("models/ml_model.pkl")


def _load_training_data() -> pd.DataFrame:
    """Load the combined positives + negatives training set.

    Priority:
      1. real_data/training_data_ml.csv (if prepare_real_data was run)
      2. negative_samples.csv + nasa_glc_enriched.csv
      3. synthetic data fallback
    """
    candidates = [
        DEFAULT_TRAINING_PATH,
        Path("real_data") / "training_data_ml.csv",
    ]
    for path in candidates:
        if path.exists():
            logger.info("Loading training data from %s", path)
            df = pd.read_csv(path)
            return _validate_columns(df)

    # Try separate positives + negatives.
    positives_path = Path("real_data") / "nasa_glc_enriched.csv"
    if not positives_path.exists():
        positives_path = Path("nasa_glc_enriched.csv")

    negatives_path = DEFAULT_NEGATIVES_PATH
    if not negatives_path.exists():
        negatives_path = Path("real_data") / "negative_samples.csv"

    if positives_path.exists() and negatives_path.exists():
        logger.info("Combining positives (%s) + negatives (%s)", positives_path, negatives_path)
        pos = pd.read_csv(positives_path)
        neg = pd.read_csv(negatives_path)
        df = pd.concat([pos, neg], ignore_index=True)
        return _validate_columns(df)

    logger.warning("No real training data found -- generating synthetic dataset")
    from generate_negative_samples import _synthetic_positives, generate_negatives
    pos = _synthetic_positives(n=200, seed=42)
    neg = generate_negatives(pos, n_per_positive=3, radius_km=5.0, seed=42)
    df = pd.concat([pos, neg], ignore_index=True)
    return _validate_columns(df)


def _validate_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Ensure all required columns exist; fill missing ones with defaults."""
    defaults = {
        "rain_1d_mm": 0.0, "rain_3d_mm": 0.0, "rain_7d_mm": 0.0, "rain_30d_mm": 0.0,
        "elevation_m": 500.0, "slope_deg": 15.0, "aspect_deg": 180.0,
        "curvature": 0.0, "susceptibility_class": 2, "lulc_class": 4,
        "vegetation_proxy": 0.5,
    }
    for col, default in defaults.items():
        if col not in df.columns:
            df[col] = default
            logger.warning("Column '%s' missing from training data -- filling with %s", col, default)
    if "landslide_label" not in df.columns:
        raise ValueError("Training data must have 'landslide_label' column")
    return df


def _spatial_holdout_split(df: pd.DataFrame):
    """Split data into train/test using spatial grouping by longitude band.

    The data-pack §2 warns: "Use spatial or temporal holdout for train/test --
    never split neighbouring pixels randomly (leakage)."

    We bin longitudes into ~1-degree bands and use GroupKFold so all samples
    in a band go to the same fold, ensuring spatial separation.
    """
    # Bin longitude into 1-degree groups.
    lon_bins = np.floor(df["longitude"].values).astype(int)
    n_unique = len(np.unique(lon_bins))

    if n_unique >= 2:
        gkf = GroupKFold(n_splits=min(5, n_unique))
        splits = list(gkf.split(df, df["landslide_label"].values, groups=lon_bins))
        train_idx, test_idx = splits[0]  # use first fold
    else:
        # Fallback to random split for small synthetic datasets.
        from sklearn.model_selection import train_test_split
        train_idx, test_idx = train_test_split(
            np.arange(len(df)), test_size=0.2, random_state=42, stratify=df["landslide_label"]
        )

    train_df = df.iloc[train_idx].copy()
    test_df = df.iloc[test_idx].copy()
    logger.info("Spatial split: train=%d, test=%d (unique lon bands=%d)",
                len(train_df), len(test_df), n_unique)
    return train_df, test_df


def train_model(df: pd.DataFrame, n_estimators: int = 200, random_state: int = 42) -> RandomForestClassifier:
    """Train a RandomForestClassifier on the prepared dataset."""
    X = df[FEATURE_COLUMNS].values.astype(float)
    y = df["landslide_label"].values.astype(int)

    train_df, test_df = _spatial_holdout_split(df)
    X_train = train_df[FEATURE_COLUMNS].values.astype(float)
    y_train = train_df["landslide_label"].values.astype(int)
    X_test = test_df[FEATURE_COLUMNS].values.astype(float)
    y_test = test_df["landslide_label"].values.astype(int)

    clf = RandomForestClassifier(
        n_estimators=n_estimators,
        max_depth=12,
        min_samples_leaf=5,
        class_weight="balanced",
        random_state=random_state,
        n_jobs=-1,
    )
    clf.fit(X_train, y_train)

    # Evaluate on the held-out spatial fold.
    y_pred = clf.predict(X_test)
    report = classification_report(y_test, y_pred, zero_division=0)
    logger.info("Model evaluation on spatial holdout:\n%s", report)

    logger.info("Feature importances:")
    for name, imp in sorted(zip(FEATURE_COLUMNS, clf.feature_importances_),
                            key=lambda x: -x[1]):
        logger.info("  %-25s %.4f", name, imp)

    return clf


def save_model(clf: RandomForestClassifier, output_path: Path = DEFAULT_MODEL_PATH) -> Path:
    """Persist model + metadata as a pickle artifact."""
    output_path.parent.mkdir(parents=True, exist_ok=True)
    artifact = {
        "model": clf,
        "feature_names": FEATURE_COLUMNS,
        "feature_importances": clf.feature_importances_.tolist(),
        "model_type": "RandomForestClassifier",
        "n_estimators": clf.n_estimators,
    }
    with open(output_path, "wb") as f:
        pickle.dump(artifact, f)
    logger.info("Saved model artifact to %s", output_path)
    return output_path


def main():
    logging.basicConfig(
        level=logging.INFO,
        format="%(asctime)s %(levelname)s %(name)s: %(message)s",
    )

    df = _load_training_data()
    n_pos = int(df["landslide_label"].sum())
    n_neg = len(df) - n_pos
    logger.info("Training dataset: %d rows (%d positive, %d negative)",
                len(df), n_pos, n_neg)

    clf = train_model(df)
    model_path = save_model(clf)

    # Emit a quick summary so the user knows it worked.
    print(f"Trained RandomForest with {clf.n_estimators} trees on {len(df)} samples")
    print(f"Top 3 features: {sorted(zip(FEATURE_COLUMNS, clf.feature_importances_), key=lambda x: -x[1])[:3]}")
    print(f"Model saved to: {model_path}")
    return model_path


if __name__ == "__main__":
    main()
